---
version: 2.1

executors:
  vm:
    machine:
      image: ubuntu-2004:current

jobs:
  build:
    executor: vm

    steps:
    - checkout
    - run: docker info
    - run: uname -a
      # Register binfmt_misc targets for cross-building
    - run: docker run --privileged linuxkit/binfmt:v0.8
    - run: make
    - run: docker images

  build_master:
    executor: vm

    steps:
    - checkout
    - run: docker info
    - run: docker run --privileged linuxkit/binfmt:v0.8
    - run: make SUFFIX=
    - run: docker images
    - run: make tag SUFFIX=
    - run: docker login -u $QUAY_LOGIN -p $QUAY_PASSWORD quay.io
    - run: make push
    - run: make manifest SUFFIX=

workflows:
  version: 2
  prometheus:
    jobs:
    - build:
        filters:
          branches:
            ignore: master
    - build_master:
        context: org-context
        filters:
          branches:
            only: master

  monthly:
    triggers:
    - schedule:
        cron: "54 10 15 * *"
        filters:
          branches:
            only:
            - master
    jobs:
    - build_master:
        context: org-context
